/*
 * mpy_bootstrap.h
 *
 * Pure-Python implementations of standard library modules missing from the
 * MicroPython embed port.  Executed once after mp_embed_init() so user
 * scripts can `import json`, `import re`, etc.
 *
 * C-string escaping:
 *   • Real newlines  → \n in C literal
 *   • Python \n etc. → chr()-based constants (_NL, _BS …)
 */

#ifndef MPY_BOOTSTRAP_H
#define MPY_BOOTSTRAP_H

static const char mpy_bootstrap_script[] =

/* ── char constants (avoids multi-level escaping) ────────────── */
"_NL=chr(10);_CR=chr(13);_TAB=chr(9);_BS=chr(92);_QT=chr(34)\n"

/* ================================================================
 * json
 * ================================================================ */
"import sys\n"
"class _Json:\n"
" @staticmethod\n"
" def dumps(o,indent=None,separators=None,sort_keys=False):\n"
"  if separators:isep,ksep=separators\n"
"  elif indent is not None:isep,ksep=',',': '\n"
"  else:isep,ksep=', ',': '\n"
"  def e(v,l):\n"
"   if v is None:return 'null'\n"
"   if v is True:return 'true'\n"
"   if v is False:return 'false'\n"
"   if isinstance(v,int):return str(v)\n"
"   if isinstance(v,float):\n"
"    s=str(v)\n"
"    if s=='inf':return 'Infinity'\n"
"    if s=='-inf':return '-Infinity'\n"
"    if s=='nan':return 'NaN'\n"
"    return s\n"
"   if isinstance(v,str):\n"
"    r=_QT\n"
"    for c in v:\n"
"     oc=ord(c)\n"
"     if c==_BS:r+=_BS+_BS\n"
"     elif c==_QT:r+=_BS+_QT\n"
"     elif c==_NL:r+=_BS+'n'\n"
"     elif c==_CR:r+=_BS+'r'\n"
"     elif c==_TAB:r+=_BS+'t'\n"
"     elif oc<32:r+=_BS+'u{:04x}'.format(oc)\n"
"     else:r+=c\n"
"    return r+_QT\n"
"   if isinstance(v,(list,tuple)):\n"
"    if not v:return '[]'\n"
"    p=[e(i,l+1) for i in v]\n"
"    if indent is not None:\n"
"     nl=_NL+' '*(indent*(l+1));el=_NL+' '*(indent*l)\n"
"     return '['+nl+(isep+nl).join(p)+el+']'\n"
"    return '['+isep.join(p)+']'\n"
"   if isinstance(v,dict):\n"
"    if not v:return '{}'\n"
"    ks=sorted(v.keys()) if sort_keys else list(v.keys())\n"
"    p=[e(str(k),l+1)+ksep+e(v[k],l+1) for k in ks]\n"
"    if indent is not None:\n"
"     nl=_NL+' '*(indent*(l+1));el=_NL+' '*(indent*l)\n"
"     return '{'+nl+(isep+nl).join(p)+el+'}'\n"
"    return '{'+isep.join(p)+'}'\n"
"   return e(str(v),l)\n"
"  return e(o,0)\n"
" @staticmethod\n"
" def loads(s):\n"
"  if isinstance(s,bytes):s=s.decode()\n"
"  n=len(s);p=[0]\n"
"  def w():\n"
"   while p[0]<n and s[p[0]] in ' \\t\\n\\r':p[0]+=1\n"
"  def v():\n"
"   w()\n"
"   if p[0]>=n:raise ValueError('unexpected end of JSON')\n"
"   c=s[p[0]]\n"
"   if c==_QT:return ps()\n"
"   if c=='{':return po()\n"
"   if c=='[':return pa()\n"
"   if s[p[0]:p[0]+4]=='true':p[0]+=4;return True\n"
"   if s[p[0]:p[0]+5]=='false':p[0]+=5;return False\n"
"   if s[p[0]:p[0]+4]=='null':p[0]+=4;return None\n"
"   return pn()\n"
"  def ps():\n"
"   p[0]+=1;r=[]\n"
"   while p[0]<n:\n"
"    c=s[p[0]]\n"
"    if c==_QT:p[0]+=1;return ''.join(r)\n"
"    if c==_BS:\n"
"     p[0]+=1;e2=s[p[0]]\n"
"     if e2=='n':r.append(_NL)\n"
"     elif e2=='r':r.append(_CR)\n"
"     elif e2=='t':r.append(_TAB)\n"
"     elif e2=='u':r.append(chr(int(s[p[0]+1:p[0]+5],16)));p[0]+=4\n"
"     elif e2=='b':r.append(chr(8))\n"
"     elif e2=='f':r.append(chr(12))\n"
"     else:r.append(e2)\n"
"    else:r.append(c)\n"
"    p[0]+=1\n"
"   raise ValueError('unterminated string')\n"
"  def pn():\n"
"   i=p[0]\n"
"   if s[p[0]]=='-':p[0]+=1\n"
"   while p[0]<n and s[p[0]].isdigit():p[0]+=1\n"
"   f=False\n"
"   if p[0]<n and s[p[0]]=='.':\n"
"    f=True;p[0]+=1\n"
"    while p[0]<n and s[p[0]].isdigit():p[0]+=1\n"
"   if p[0]<n and s[p[0]] in 'eE':\n"
"    f=True;p[0]+=1\n"
"    if p[0]<n and s[p[0]] in '+-':p[0]+=1\n"
"    while p[0]<n and s[p[0]].isdigit():p[0]+=1\n"
"   t=s[i:p[0]]\n"
"   return float(t) if f else int(t)\n"
"  def pa():\n"
"   p[0]+=1;r=[];w()\n"
"   if p[0]<n and s[p[0]]==']':p[0]+=1;return r\n"
"   while True:\n"
"    r.append(v());w()\n"
"    if p[0]<n and s[p[0]]==',':p[0]+=1\n"
"    else:break\n"
"   w()\n"
"   if p[0]<n and s[p[0]]==']':p[0]+=1\n"
"   return r\n"
"  def po():\n"
"   p[0]+=1;r={};w()\n"
"   if p[0]<n and s[p[0]]=='}':p[0]+=1;return r\n"
"   while True:\n"
"    w();k=ps();w();p[0]+=1\n"
"    r[k]=v();w()\n"
"    if p[0]<n and s[p[0]]==',':p[0]+=1\n"
"    else:break\n"
"   w()\n"
"   if p[0]<n and s[p[0]]=='}':p[0]+=1\n"
"   return r\n"
"  return v()\n"
"sys.modules['json']=_Json\n"

/* ================================================================
 * re  — recursive backtracking regex engine
 * Supports: . * + ? ^ $ [] [^] \\d \\w \\s \\D \\W \\S () | {n,m}
 * ================================================================ */
"class _Re:\n"
" IGNORECASE=2;MULTILINE=8;DOTALL=16;I=2;M=8;S=16\n"
" class _Match:\n"
"  def __init__(self,s,gs):\n"
"   self.string=s;self._gs=gs\n"
"  def group(self,*a):\n"
"   if not a:a=(0,)\n"
"   if len(a)==1:\n"
"    s2,e2=self._gs[a[0]]\n"
"    return self.string[s2:e2] if s2>=0 else None\n"
"   return tuple(self.group(i) for i in a)\n"
"  def groups(self,default=None):\n"
"   return tuple(self.string[s2:e2] if s2>=0 else default for s2,e2 in self._gs[1:])\n"
"  def start(self,g=0):return self._gs[g][0]\n"
"  def end(self,g=0):return self._gs[g][1]\n"
"  def span(self,g=0):return self._gs[g]\n"
" @staticmethod\n"
" def _pcc(p,i,n):\n"
"  neg=False\n"
"  if i<n and p[i]=='^':neg=True;i+=1\n"
"  cs=set()\n"
"  while i<n and p[i]!=']':\n"
"   if p[i]==_BS and i+1<n:\n"
"    i+=1;c=p[i]\n"
"    if c=='d':cs.update('0123456789')\n"
"    elif c=='w':cs.update('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_')\n"
"    elif c=='s':cs.update(' \\t\\n\\r')\n"
"    else:cs.add(c)\n"
"    i+=1\n"
"   elif i+2<n and p[i+1]=='-' and p[i+2]!=']':\n"
"    for o in range(ord(p[i]),ord(p[i+2])+1):cs.add(chr(o))\n"
"    i+=3\n"
"   else:cs.add(p[i]);i+=1\n"
"  return cs,neg,i+1\n"
" @staticmethod\n"
" def _tok(p):\n"
"  r=[];i=0;n=len(p);gc=0\n"
"  while i<n:\n"
"   c=p[i]\n"
"   if c==_BS and i+1<n:\n"
"    i+=1;r.append(('esc',p[i]));i+=1\n"
"   elif c=='.':r.append(('dot',0));i+=1\n"
"   elif c=='^':r.append(('as',0));i+=1\n"
"   elif c=='$':r.append(('ae',0));i+=1\n"
"   elif c=='[':\n"
"    cs,neg,i=_Re._pcc(p,i+1,n)\n"
"    r.append(('cls',(cs,neg)))\n"
"   elif c=='(':gc+=1;r.append(('gs',gc));i+=1\n"
"   elif c==')':r.append(('ge',0));i+=1\n"
"   elif c=='|':r.append(('alt',0));i+=1\n"
"   elif c in '*+?':\n"
"    if c=='*':r.append(('q',(0,999)))\n"
"    elif c=='+':r.append(('q',(1,999)))\n"
"    else:r.append(('q',(0,1)))\n"
"    i+=1\n"
"   elif c=='{':\n"
"    j=p.find('}',i)\n"
"    if j<0:r.append(('lit',c));i+=1;continue\n"
"    sp=p[i+1:j]\n"
"    if ',' in sp:\n"
"     pp=sp.split(',')\n"
"     mn=int(pp[0]) if pp[0].strip() else 0\n"
"     mx=int(pp[1]) if pp[1].strip() else 999\n"
"    else:mn=int(sp);mx=mn\n"
"    r.append(('q',(mn,mx)));i=j+1\n"
"   else:r.append(('lit',c));i+=1\n"
"  return r,gc\n"
" @staticmethod\n"
" def _mc(tp,vl,ch,fl):\n"
"  if tp=='lit':\n"
"   if fl&2:return ch.lower()==vl.lower()\n"
"   return ch==vl\n"
"  if tp=='dot':return (fl&16) or ch!=_NL\n"
"  if tp=='esc':\n"
"   v=vl\n"
"   if v=='d':return ch.isdigit()\n"
"   if v=='D':return not ch.isdigit()\n"
"   if v=='w':return ch.isalnum() or ch=='_'\n"
"   if v=='W':return not(ch.isalnum() or ch=='_')\n"
"   if v=='s':return ch in ' \\t\\n\\r'\n"
"   if v=='S':return ch not in ' \\t\\n\\r'\n"
"   return ch==v\n"
"  if tp=='cls':\n"
"   cs,neg=vl\n"
"   return (ch not in cs) if neg else (ch in cs)\n"
"  return False\n"
" @staticmethod\n"
" def _run(tks,ti,s,si,end,gs,fl):\n"
"  while ti<len(tks):\n"
"   tp,vl=tks[ti]\n"
"   if tp=='alt':\n"
"    rest=ti+1\n"
"    r=_Re._run(tks,rest,s,si,end,gs,fl)\n"
"    if r>=0:return r\n"
"    depth=0\n"
"    while rest<len(tks):\n"
"     t2,_=tks[rest]\n"
"     if t2=='gs':depth+=1\n"
"     elif t2=='ge':depth-=1\n"
"     if depth<0:break\n"
"     if depth==0 and t2=='alt':\n"
"      r=_Re._run(tks,rest+1,s,si,end,gs,fl)\n"
"      if r>=0:return r\n"
"     rest+=1\n"
"    return -1\n"
"   if tp=='as':\n"
"    if si!=0 and not(fl&8 and si>0 and s[si-1]==_NL):return -1\n"
"    ti+=1;continue\n"
"   if tp=='ae':\n"
"    if si!=end and not(fl&8 and si<end and s[si]==_NL):return -1\n"
"    ti+=1;continue\n"
"   if tp=='gs':\n"
"    gs[vl]=(si,-1);ti+=1;continue\n"
"   if tp=='ge':\n"
"    for g in range(len(gs)-1,-1,-1):\n"
"     if gs[g][1]<0:gs[g]=(gs[g][0],si);break\n"
"    ti+=1;continue\n"
"   mn,mx=1,1\n"
"   if ti+1<len(tks) and tks[ti+1][0]=='q':\n"
"    mn,mx=tks[ti+1][1];ti+=1\n"
"   ps2=[si];cnt=0\n"
"   while cnt<mx and ps2[-1]<end:\n"
"    if _Re._mc(tp,vl,s[ps2[-1]],fl):ps2.append(ps2[-1]+1);cnt+=1\n"
"    else:break\n"
"   for c2 in range(len(ps2)-1,mn-1,-1):\n"
"    sg=list(gs)\n"
"    r=_Re._run(tks,ti+1,s,ps2[c2],end,gs,fl)\n"
"    if r>=0:return r\n"
"    gs[:]=sg\n"
"   return -1\n"
"  return si\n"
" class _Pat:\n"
"  def __init__(self,p,fl=0):\n"
"   self.pattern=p;self.flags=fl;self._t,self._ng=_Re._tok(p)\n"
"  def _gs0(self):return [(-1,-1)]*(self._ng+1)\n"
"  def search(self,s,pos=0,endpos=None):\n"
"   end=len(s) if endpos is None else endpos\n"
"   for i in range(pos,end+1):\n"
"    gs=self._gs0()\n"
"    r=_Re._run(self._t,0,s,i,end,gs,self.flags)\n"
"    if r>=0:\n"
"     gs[0]=(i,r)\n"
"     return _Re._Match(s,gs)\n"
"   return None\n"
"  def match(self,s,pos=0,endpos=None):\n"
"   end=len(s) if endpos is None else endpos\n"
"   gs=self._gs0()\n"
"   r=_Re._run(self._t,0,s,pos,end,gs,self.flags)\n"
"   if r>=0:gs[0]=(pos,r);return _Re._Match(s,gs)\n"
"   return None\n"
"  def findall(self,s,pos=0,endpos=None):\n"
"   end=len(s) if endpos is None else endpos;r=[];i=pos\n"
"   while i<=end:\n"
"    gs=self._gs0()\n"
"    m=_Re._run(self._t,0,s,i,end,gs,self.flags)\n"
"    if m<0:i+=1;continue\n"
"    gs[0]=(i,m)\n"
"    if self._ng==0:r.append(s[i:m])\n"
"    elif self._ng==1:s2,e2=gs[1];r.append(s[s2:e2] if s2>=0 else '')\n"
"    else:r.append(tuple(s[s2:e2] if s2>=0 else '' for s2,e2 in gs[1:]))\n"
"    i=m if m>i else i+1\n"
"   return r\n"
"  def sub(self,repl,s,count=0):\n"
"   r=[];i=0;n=len(s);c2=0\n"
"   while i<=n:\n"
"    gs=self._gs0()\n"
"    m=_Re._run(self._t,0,s,i,n,gs,self.flags)\n"
"    if m<0:r.append(s[i]) if i<n else None;i+=1;continue\n"
"    gs[0]=(i,m)\n"
"    r.append(s[c2:i] if c2<i else '')\n"
"    if callable(repl):\n"
"     mo=_Re._Match(s,gs);r.append(repl(mo))\n"
"    else:r.append(repl)\n"
"    c2=m;i=m if m>i else i+1\n"
"    if count>0:\n"
"     count-=1\n"
"     if count==0:r.append(s[c2:]);return ''.join(r)\n"
"   return ''.join(r)\n"
"  def split(self,s,maxsplit=0):\n"
"   r=[];i=0;n=len(s);c2=0\n"
"   while i<=n:\n"
"    gs=self._gs0()\n"
"    m=_Re._run(self._t,0,s,i,n,gs,self.flags)\n"
"    if m<0:i+=1;continue\n"
"    r.append(s[c2:i]);c2=m;i=m if m>i else i+1\n"
"    if maxsplit>0 and len(r)>=maxsplit:break\n"
"   r.append(s[c2:])\n"
"   return r\n"
" @staticmethod\n"
" def compile(p,fl=0):return _Re._Pat(p,fl)\n"
" @staticmethod\n"
" def search(p,s,fl=0):return _Re._Pat(p,fl).search(s)\n"
" @staticmethod\n"
" def match(p,s,fl=0):return _Re._Pat(p,fl).match(s)\n"
" @staticmethod\n"
" def findall(p,s,fl=0):return _Re._Pat(p,fl).findall(s)\n"
" @staticmethod\n"
" def sub(p,repl,s,count=0,flags=0):return _Re._Pat(p,flags).sub(repl,s,count)\n"
" @staticmethod\n"
" def split(p,s,maxsplit=0,flags=0):return _Re._Pat(p,flags).split(s,maxsplit)\n"
"sys.modules['re']=_Re\n"

/* ================================================================
 * datetime — basic date/time types
 * ================================================================ */
"class _timedelta:\n"
" def __init__(self,days=0,seconds=0,microseconds=0,milliseconds=0,minutes=0,hours=0,weeks=0):\n"
"  us=microseconds+milliseconds*1000\n"
"  s2=seconds+minutes*60+hours*3600\n"
"  d=days+weeks*7\n"
"  us_total=us+s2*1000000+d*86400*1000000\n"
"  self.days=us_total//86400000000\n"
"  rem=us_total-self.days*86400000000\n"
"  self.seconds=rem//1000000\n"
"  self.microseconds=rem%1000000\n"
" def total_seconds(self):return self.days*86400+self.seconds+self.microseconds/1e6\n"
" def __repr__(self):return 'datetime.timedelta(days=%d, seconds=%d, microseconds=%d)'%(self.days,self.seconds,self.microseconds)\n"
" def __str__(self):\n"
"  h=self.seconds//3600;m=(self.seconds%3600)//60;s2=self.seconds%60\n"
"  r='';neg=False\n"
"  if self.days<0:neg=True\n"
"  if self.days:r=str(self.days)+' day'+('s' if abs(self.days)!=1 else '')+', '\n"
"  r+='%d:%02d:%02d'%(h,m,s2)\n"
"  if self.microseconds:r+='.%06d'%self.microseconds\n"
"  return r\n"
" def __add__(self,o):return _timedelta(microseconds=(self.days*86400+self.seconds)*1000000+self.microseconds+(o.days*86400+o.seconds)*1000000+o.microseconds)\n"
" def __sub__(self,o):return _timedelta(microseconds=(self.days*86400+self.seconds)*1000000+self.microseconds-((o.days*86400+o.seconds)*1000000+o.microseconds))\n"
" def __eq__(self,o):return isinstance(o,_timedelta) and self.days==o.days and self.seconds==o.seconds and self.microseconds==o.microseconds\n"
"\n"
"class _date:\n"
" def __init__(self,year,month,day):\n"
"  self.year=year;self.month=month;self.day=day\n"
" def isoformat(self):return '%04d-%02d-%02d'%(self.year,self.month,self.day)\n"
" def __repr__(self):return 'datetime.date(%d, %d, %d)'%(self.year,self.month,self.day)\n"
" def __str__(self):return self.isoformat()\n"
" def __eq__(self,o):return isinstance(o,_date) and self.year==o.year and self.month==o.month and self.day==o.day\n"
" def __sub__(self,o):\n"
"  if isinstance(o,_date):\n"
"   d1=_date._toord(self);d2=_date._toord(o)\n"
"   return _timedelta(days=d1-d2)\n"
"  if isinstance(o,_timedelta):return _date._fromord(_date._toord(self)-o.days)\n"
"  raise TypeError('unsupported operand')\n"
" def __add__(self,o):\n"
"  if isinstance(o,_timedelta):return _date._fromord(_date._toord(self)+o.days)\n"
"  raise TypeError('unsupported operand')\n"
" def weekday(self):return (_date._toord(self)+6)%7\n"
" @staticmethod\n"
" def _toord(d):\n"
"  y=d.year;m=d.month;dy=d.day\n"
"  if m<=2:y-=1;m+=12\n"
"  return 365*y+y//4-y//100+y//400+(153*(m-3)+2)//5+dy-307\n"
" @staticmethod\n"
" def _fromord(n):\n"
"  n+=307;y=(10000*n+14780)//3652425\n"
"  d2=n-(365*y+y//4-y//100+y//400)\n"
"  if d2<0:y-=1;d2=n-(365*y+y//4-y//100+y//400)\n"
"  mi=(100*d2+52)//3060;m=mi+3 if mi<10 else mi-9\n"
"  y=y+(1 if m<=2 else 0)\n"
"  dy=d2-(mi*3060+52)//100+1\n"
"  return _date(y,m,dy)\n"
" @staticmethod\n"
" def today():\n"
"  try:t=__get_time();d=int(t)//86400;return _date._fromord(d+719163)\n"
"  except:return _date(2025,1,1)\n"
"\n"
"class _datetime:\n"
" def __init__(self,year,month,day,hour=0,minute=0,second=0,microsecond=0):\n"
"  self.year=year;self.month=month;self.day=day\n"
"  self.hour=hour;self.minute=minute;self.second=second;self.microsecond=microsecond\n"
" def date(self):return _date(self.year,self.month,self.day)\n"
" def isoformat(self,sep='T'):\n"
"  s='%04d-%02d-%02d%s%02d:%02d:%02d'%(self.year,self.month,self.day,sep,self.hour,self.minute,self.second)\n"
"  if self.microsecond:s+='.%06d'%self.microsecond\n"
"  return s\n"
" def timestamp(self):\n"
"  d=_date._toord(_date(self.year,self.month,self.day))-719163\n"
"  return d*86400+self.hour*3600+self.minute*60+self.second+self.microsecond/1e6\n"
" def strftime(self,fmt):\n"
"  r=fmt\n"
"  r=r.replace('%Y','%04d'%self.year).replace('%m','%02d'%self.month).replace('%d','%02d'%self.day)\n"
"  r=r.replace('%H','%02d'%self.hour).replace('%M','%02d'%self.minute).replace('%S','%02d'%self.second)\n"
"  return r\n"
" def __repr__(self):return 'datetime.datetime(%d, %d, %d, %d, %d, %d)'%(self.year,self.month,self.day,self.hour,self.minute,self.second)\n"
" def __str__(self):return self.isoformat(' ')\n"
" def __sub__(self,o):\n"
"  if isinstance(o,_datetime):return _timedelta(seconds=int(self.timestamp()-o.timestamp()))\n"
"  if isinstance(o,_timedelta):\n"
"   ts=self.timestamp()-o.total_seconds()\n"
"   return _datetime.fromtimestamp(ts)\n"
"  raise TypeError('unsupported operand')\n"
" def __add__(self,o):\n"
"  if isinstance(o,_timedelta):return _datetime.fromtimestamp(self.timestamp()+o.total_seconds())\n"
"  raise TypeError('unsupported operand')\n"
" def __eq__(self,o):return isinstance(o,_datetime) and self.timestamp()==o.timestamp()\n"
" @staticmethod\n"
" def now():\n"
"  try:\n"
"   t=__get_time();ts=int(t)\n"
"   d=ts//86400;rem=ts%86400;h=rem//3600;m2=(rem%3600)//60;s2=rem%60\n"
"   dt=_date._fromord(d+719163)\n"
"   return _datetime(dt.year,dt.month,dt.day,h,m2,s2)\n"
"  except:return _datetime(2025,1,1)\n"
" @staticmethod\n"
" def fromtimestamp(ts):\n"
"  ts=int(ts);d=ts//86400;rem=ts%86400\n"
"  h=rem//3600;m2=(rem%3600)//60;s2=rem%60\n"
"  dt=_date._fromord(d+719163)\n"
"  return _datetime(dt.year,dt.month,dt.day,h,m2,s2)\n"
" @staticmethod\n"
" def fromisoformat(s2):\n"
"  s2=s2.replace('T',' ')\n"
"  dp=s2.split(' ')[0].split('-');tp=[0,0,0]\n"
"  if ' ' in s2:tp2=s2.split(' ')[1].split(':');tp=[int(x.split('.')[0]) for x in tp2]\n"
"  return _datetime(int(dp[0]),int(dp[1]),int(dp[2]),*tp)\n"
"\n"
"class _DT:\n"
" datetime=_datetime;date=_date;timedelta=_timedelta\n"
"sys.modules['datetime']=_DT\n"

/* ================================================================
 * base64
 * ================================================================ */
"class _Base64:\n"
" _T='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'\n"
" @staticmethod\n"
" def b64encode(data):\n"
"  if isinstance(data,str):data=data.encode()\n"
"  t=_Base64._T;r='';i=0;n=len(data)\n"
"  while i<n:\n"
"   b1=data[i];b2=data[i+1] if i+1<n else 0;b3=data[i+2] if i+2<n else 0\n"
"   r+=t[b1>>2]+t[((b1&3)<<4)|(b2>>4)]\n"
"   r+=t[((b2&15)<<2)|(b3>>6)] if i+1<n else '='\n"
"   r+=t[b3&63] if i+2<n else '='\n"
"   i+=3\n"
"  return r.encode()\n"
" @staticmethod\n"
" def b64decode(s):\n"
"  if isinstance(s,bytes):s=s.decode()\n"
"  t=_Base64._T;r=[];buf=0;bits=0\n"
"  for c in s:\n"
"   if c in ' \\t\\n\\r':continue\n"
"   if c=='=':break\n"
"   v=t.find(c)\n"
"   if v<0:continue\n"
"   buf=(buf<<6)|v;bits+=6\n"
"   if bits>=8:bits-=8;r.append((buf>>bits)&255)\n"
"  return bytes(r)\n"
" @staticmethod\n"
" def b16encode(data):\n"
"  if isinstance(data,str):data=data.encode()\n"
"  return ''.join('%02X'%b for b in data).encode()\n"
" @staticmethod\n"
" def b16decode(s):\n"
"  if isinstance(s,bytes):s=s.decode()\n"
"  return bytes(int(s[i:i+2],16) for i in range(0,len(s),2))\n"
" encodebytes=b64encode\n"
" decodebytes=b64decode\n"
"sys.modules['base64']=_Base64\n"

/* ================================================================
 * random  (linear congruential generator)
 * ================================================================ */
"class _Random:\n"
" _s=6651\n"
" @staticmethod\n"
" def seed(v=None):\n"
"  if v is None:\n"
"   try:_Random._s=int(__get_time()*1000)&0xFFFFFFFF;return\n"
"   except:pass\n"
"  _Random._s=int(v)&0xFFFFFFFF\n"
" @staticmethod\n"
" def _next():\n"
"  _Random._s=(_Random._s*1103515245+12345)&0x7FFFFFFF\n"
"  return _Random._s\n"
" @staticmethod\n"
" def random():return _Random._next()/0x7FFFFFFF\n"
" @staticmethod\n"
" def randint(a,b):return a+_Random._next()%(b-a+1)\n"
" @staticmethod\n"
" def randrange(start,stop=None,step=1):\n"
"  if stop is None:start,stop=0,start\n"
"  n=(stop-start+step-1)//step\n"
"  return start+step*(_Random._next()%n)\n"
" @staticmethod\n"
" def choice(seq):return seq[_Random._next()%len(seq)]\n"
" @staticmethod\n"
" def shuffle(x):\n"
"  for i in range(len(x)-1,0,-1):\n"
"   j=_Random._next()%(i+1);x[i],x[j]=x[j],x[i]\n"
" @staticmethod\n"
" def uniform(a,b):return a+(b-a)*_Random.random()\n"
" @staticmethod\n"
" def sample(pop,k):\n"
"  p=list(pop);r=[]\n"
"  for _ in range(k):j=_Random._next()%len(p);r.append(p.pop(j))\n"
"  return r\n"
"sys.modules['random']=_Random\n"

/* ================================================================
 * time  (basic: time(), monotonic(), sleep stub)
 * ================================================================ */
"class _Time:\n"
" @staticmethod\n"
" def time():\n"
"  try:return __get_time()\n"
"  except:return 0.0\n"
" @staticmethod\n"
" def monotonic():return _Time.time()\n"
" @staticmethod\n"
" def sleep(secs):pass\n"
" @staticmethod\n"
" def localtime(t=None):\n"
"  if t is None:t=_Time.time()\n"
"  t=int(t);d=t//86400;rem=t%86400;h=rem//3600;m=(rem%3600)//60;s=rem%60\n"
"  dt=_date._fromord(d+719163)\n"
"  wd=(d+3)%7\n"
"  yday=d-_date._toord(_date(dt.year,1,1))+719163+1\n"
"  return (dt.year,dt.month,dt.day,h,m,s,wd,yday,-1)\n"
" @staticmethod\n"
" def mktime(t):return _datetime(t[0],t[1],t[2],t[3],t[4],t[5]).timestamp()\n"
"sys.modules['time']=_Time\n"

/* ================================================================
 * heapq
 * ================================================================ */
"class _Heapq:\n"
" @staticmethod\n"
" def heappush(h,item):\n"
"  h.append(item);i=len(h)-1\n"
"  while i>0:\n"
"   p=(i-1)//2\n"
"   if h[i]<h[p]:h[i],h[p]=h[p],h[i];i=p\n"
"   else:break\n"
" @staticmethod\n"
" def heappop(h):\n"
"  if len(h)==1:return h.pop()\n"
"  top=h[0];h[0]=h.pop();n=len(h);i=0\n"
"  while True:\n"
"   l=2*i+1;r=2*i+2;s=i\n"
"   if l<n and h[l]<h[s]:s=l\n"
"   if r<n and h[r]<h[s]:s=r\n"
"   if s!=i:h[i],h[s]=h[s],h[i];i=s\n"
"   else:break\n"
"  return top\n"
" @staticmethod\n"
" def heapify(h):\n"
"  for i in range(len(h)//2-1,-1,-1):_Heapq._sd(h,i,len(h))\n"
" @staticmethod\n"
" def _sd(h,i,n):\n"
"  while True:\n"
"   l=2*i+1;r=2*i+2;s=i\n"
"   if l<n and h[l]<h[s]:s=l\n"
"   if r<n and h[r]<h[s]:s=r\n"
"   if s!=i:h[i],h[s]=h[s],h[i];i=s\n"
"   else:break\n"
" @staticmethod\n"
" def nsmallest(n,it):l=sorted(it);return l[:n]\n"
" @staticmethod\n"
" def nlargest(n,it):l=sorted(it,reverse=True);return l[:n]\n"
"sys.modules['heapq']=_Heapq\n"

/* ================================================================
 * binascii
 * ================================================================ */
"class _Binascii:\n"
" @staticmethod\n"
" def hexlify(data):return ''.join('{:02x}'.format(b) for b in data).encode()\n"
" @staticmethod\n"
" def unhexlify(h):\n"
"  if isinstance(h,bytes):h=h.decode()\n"
"  return bytes(int(h[i:i+2],16) for i in range(0,len(h),2))\n"
" @staticmethod\n"
" def b2a_base64(data,newline=True):\n"
"  r=_Base64.b64encode(data)\n"
"  if isinstance(r,bytes):r=r.decode()\n"
"  if newline:r+=_NL\n"
"  return r.encode()\n"
" @staticmethod\n"
" def a2b_base64(s):return _Base64.b64decode(s)\n"
"sys.modules['binascii']=_Binascii\n"

/* ================================================================
 * hashlib  (SHA-256, pure Python)
 * ================================================================ */
"class _SHA256:\n"
" _K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,\n"
"     0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,\n"
"     0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,\n"
"     0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,\n"
"     0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,\n"
"     0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,\n"
"     0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,\n"
"     0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]\n"
" def __init__(self,data=b''):\n"
"  self._h=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]\n"
"  self._buf=b'';self._count=0;self.block_size=64;self.digest_size=32\n"
"  if data:self.update(data)\n"
" def _rotr(self,x,n):return((x>>n)|(x<<(32-n)))&0xFFFFFFFF\n"
" def _compress(self,block):\n"
"  K=_SHA256._K;w=[0]*64\n"
"  for i in range(16):w[i]=int.from_bytes(block[i*4:i*4+4],'big')\n"
"  for i in range(16,64):\n"
"   s0=self._rotr(w[i-15],7)^self._rotr(w[i-15],18)^(w[i-15]>>3)\n"
"   s1=self._rotr(w[i-2],17)^self._rotr(w[i-2],19)^(w[i-2]>>10)\n"
"   w[i]=(w[i-16]+s0+w[i-7]+s1)&0xFFFFFFFF\n"
"  a,b,c,d,e,f,g,h=self._h\n"
"  for i in range(64):\n"
"   S1=self._rotr(e,6)^self._rotr(e,11)^self._rotr(e,25)\n"
"   ch=(e&f)^((~e)&g)\n"
"   t1=(h+S1+ch+K[i]+w[i])&0xFFFFFFFF\n"
"   S0=self._rotr(a,2)^self._rotr(a,13)^self._rotr(a,22)\n"
"   mj=(a&b)^(a&c)^(b&c)\n"
"   t2=(S0+mj)&0xFFFFFFFF\n"
"   h=g;g=f;f=e;e=(d+t1)&0xFFFFFFFF;d=c;c=b;b=a;a=(t1+t2)&0xFFFFFFFF\n"
"  for i,v in enumerate([a,b,c,d,e,f,g,h]):self._h[i]=(self._h[i]+v)&0xFFFFFFFF\n"
" def update(self,data):\n"
"  if isinstance(data,str):data=data.encode()\n"
"  self._buf+=data;self._count+=len(data)\n"
"  while len(self._buf)>=64:self._compress(self._buf[:64]);self._buf=self._buf[64:]\n"
" def digest(self):\n"
"  buf=self._buf;cnt=self._count\n"
"  pad=b'\\x80'+b'\\x00'*((55-len(buf))%64)\n"
"  tail=buf+pad+(cnt*8).to_bytes(8,'big')\n"
"  h=list(self._h)\n"
"  for i in range(0,len(tail),64):self._compress(tail[i:i+64])\n"
"  d=b''.join(v.to_bytes(4,'big') for v in self._h)\n"
"  self._h=h\n"
"  return d\n"
" def hexdigest(self):return ''.join('{:02x}'.format(b) for b in self.digest())\n"
" def copy(self):\n"
"  c=_SHA256();c._h=list(self._h);c._buf=self._buf;c._count=self._count\n"
"  return c\n"
"class _Hashlib:\n"
" @staticmethod\n"
" def sha256(data=b''):return _SHA256(data)\n"
" @staticmethod\n"
" def new(name,data=b''):\n"
"  if name=='sha256':return _SHA256(data)\n"
"  raise ValueError('unsupported hash: '+name)\n"
"sys.modules['hashlib']=_Hashlib\n"

/* ── done ─────────────────────────────────────────────────────── */
;

#endif /* MPY_BOOTSTRAP_H */
